runtime: python
env: flex
runtime_config:
    python_version: 3.8

resources:
    cpu: 1
    memory_gb: 4
    disk_size_gb: 8
    
handlers:
- url: /static
  static_dir: static/
  
- url: /.*
  script: auto
