runtime: python
env: flex
runtime_config:
    python_version: 3.7

resources:
    cpu: 2
    memory_gb: 8
    disk_size_gb: 32
    
handlers:
- url: /static
  static_dir: static/
  
- url: /.*
  script: auto
