runtime: python
env: flex
runtime_config:
    python_version: 3.7
entrypoint: gunicorn -b :$PORT project_name.wsgi

resources:
    cpu: 2
    memory_gb: 4
    disk_size_gb: 16
    
handlers:
- url: /static
  static_dir: static/
  
- url: /.*
  script: auto
