# conda env export -f conda.yaml
name: venv
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8.8
  - pip
  - pip:
    - numpy
    - matplotlib
    - opencv-python
    - torch
    - torchvision
    - easydict
    - python-dotenv
    - mlflow